name: 'Docker Deploy Action'
description: 'Deploy your Docker image using username password or SSH key-based authentication'

inputs:
    remote_host:
        description: 'SSH host for deployment'
        required: true
    ssh_port:
        description: 'Port for key-scanning the server'
        required: false
        default: '22'
    ssh_username:
        description: 'SSH username for authentication'
        required: true
    ssh_password:
        description: 'SSH password for deployment'
        required: true
    ssh_private_key:
        description: 'SSH private key for authentication'
        required: true
    command:
        description: 'Command to run on the remote host'
        required: true

runs:
    using: docker
    image: Dockerfile

branding:
    icon: 'upload-cloud'
    color: 'blue'