name: 'Docker Deploy Action'
description: 'Deploy your Docker image using username password or SSH key-based authentication'
author: 'Andrew Osenga'

inputs:
    host:
        description: 'ssh remote host'
        required: true
    port:
        description: 'ssh remote port'
        default: 22
    user:
        description: 'ssh remote user'
        required: true
    key:
        description: 'content of ssh private key. ex raw content of ~/.ssh/id_rsa'
        required: false
    pass:
        description: 'ssh remote password'
        required: false
    connect_timeout:
        description: 'connection timeout to remote host'
        default: "30s"
        required: false
    script:
        description: 'execute commands on ssh'
        required: false

runs:
    using: docker
    image: Dockerfile

branding:
    icon: 'upload-cloud'
    color: 'blue'